version: '3'

services:
    meetbluesfu:
        image: dbw/meetblue:development
        build:
            context: .
            dockerfile: DockerfileDevelopment
        container_name: meetblue_development
        hostname: meetbluesfu
        restart: unless-stopped
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
            # These volumes are not mandatory, comment if you want to use it
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
